#!/bin/bash
set -e

echo "  [mediaSnare] postinst running..."

chmod 755 /usr/bin/mediasnare

glib-compile-schemas /usr/share/glib-2.0/schemas/ 2>/dev/null || true

gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true
gtk-update-icon-cache -f -t /usr/share/icons/lean-icons 2>/dev/null || true

echo "  [mediaSnare] install complete."
